checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - vendor/*
        - app/*
        - bin/*
        - web/*
        - spec/*

before_commands:
  - "composer install --prefer-source"

tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cs_fixer: true
    sensiolabs_security_checker: true
